// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModularMonolith.Modules.ReadModel.Persistance.ReadModel.Contractors;

[Table("Addresses", Schema = "CnM")]
public partial class ContractorAddressEntity {
    [StringLength(5)]
    public string TypeId { get; set; } = null!;

    [Key]
    public int Id { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public string? Line1 { get; set; }

    public string? Line2 { get; set; }

    [StringLength(20)]
    public string? PostalCode { get; set; }

    [StringLength(30)]
    public string? City { get; set; }

    [StringLength(2)]
    public string? Country { get; set; }

    public bool IsDefault { get; set; }

    [ForeignKey("ContractorId")]
    public ContractorEntity Contractor { get; set; } = default!;
}