// <auto-generated />
using System.Runtime.CompilerServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: InternalsVisibleTo("Kubis1982.Shared.DomainTests")]
[assembly: InternalsVisibleTo("Kubis1982.Shared.Infrastructure")]
