// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ModularMonolith.Modules.ReadModel.Persistance.ReadModel.Entities;

[Table("Users", Schema = "ACM")]
public partial class UserEntity
{
    [StringLength(5)]
    [Unicode(false)]
    public string TypeId { get; set; } = null!;

    [Key]
    public int Id { get; set; }

    [Precision(2)]
    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    [Precision(2)]
    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    [StringLength(20)]
    public string Name { get; set; } = null!;

    [StringLength(30)]
    public string? Email { get; set; }

    public bool? IsBlocked { get; set; }

    [StringLength(20)]
    public string? FirstName { get; set; }

    [StringLength(20)]
    public string? MiddleName { get; set; }

    [StringLength(20)]
    public string? LastName { get; set; }

    public bool? RequirePasswordReset { get; set; }

    public int RoleId { get; set; }
}