// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModularMonolith.Modules.ReadModel.Persistance.ReadModel.Articles;

[Table("Articles", Schema = "ArM")]
public partial class ArticleEntity {
    [StringLength(5)]
    public string TypeId { get; set; } = null!;

    [Key]
    public int Id { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    [StringLength(10)]
    public string Unit { get; set; } = null!;

    public string? Description { get; set; }

    public bool IsBlocked { get; set; }
}