// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModularMonolith.Modules.ReadModel.Persistance.ReadModel.Ordering;

[Table("Orders", Schema = "OrM")]
public partial class OrderEntity {
    [StringLength(5)]
    public string TypeId { get; set; } = null!;

    [Key]
    public int Id { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    [StringLength(5)]
    [Obsolete]
    public string ContractorTypeId { get; set; } = null!;

    public Contractors.ContractorEntity Contractor { get; set; } = default!;

    [StringLength(5)]
    [Obsolete]
    public string WarehouseTypeId { get; set; } = null!;

    public Warehouses.WarehouseEntity Warehouse { get; set; } = default!;

    public DateTime? ExecutionDate { get; set; }

    public byte Status { get; set; }
    public string? OrderNo { get; set; }
    public byte OrderType { get; set; }

    public string? Description { get; set; }

    public string? AddressLine1 { get; set; }
    public string? AddressLine2 { get; set; }
    [StringLength(20)]
    public string? AddressPostalCode { get; set; }
    [StringLength(30)]
    public string? AddressCity { get; set; }
    [StringLength(2)]
    public string? AddressCountry { get; set; }
}