// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModularMonolith.Modules.ReadModel.Persistance.ReadModel.Ordering;

[Table("OrderItems", Schema = "OrM")]
public partial class OrderItemEntity {
    [StringLength(5)]
    public string TypeId { get; set; } = null!;

    [Key]
    public int Id { get; set; }
    
    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public OrderEntity Order { get; set; } = default!;

    public short Position { get; set; }

    [StringLength(5)]
    [Obsolete]
    public string ArticleTypeId { get; set; } = null!;

    public Articles.ArticleEntity Article { get; set; } = default!;  

    public decimal Quantity { get; set; }

    [StringLength(10)]
    public string QuantityUnit { get; set; } = null!;

    public int QuantityNumerator { get; set; }

    public int QuantityDenominator { get; set; }

    public string? Description { get; set; }

    public decimal? QuantityCompleted { get; set; }
}