// <auto-generated />
using System.Runtime.CompilerServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: InternalsVisibleTo("ModularMonolith.Modules.Warehouses.DomainTests")]
[assembly: InternalsVisibleTo("ModularMonolith.Modules.Warehouses.Infrastructure")]
