# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.100
    - name: Restore dependencies
      run: dotnet restore ModularMonolith.sln
    - name: Build
      run: dotnet build ModularMonolith.sln --no-restore
    - name: Architecture tests
      run: dotnet test ModularMonolith.sln --no-build --verbosity normal --filter "Category=Architecture"  
    - name: Domain tests
      run: dotnet test ModularMonolith.sln --no-build --verbosity normal --filter "Category=Domain"
    - name: Api tests
      run: dotnet test ModularMonolith.sln --no-build --verbosity normal --filter "Category=Api"
